### ISSUE TITLE
epub3.0报错：No Section Found

### ISSUE THREAD

**Issue by snolkmg** [jinhuan138/vue-reader#1]
> Uncaught runtime errors:
> ×
> ERROR
> No Section Found
>     at Rendition._display (webpack-internal:///./node_modules/epubjs/src/rendition.js:355:31)
>     at Queue.dequeue (webpack-internal:///./node_modules/epubjs/src/utils/queue.js:86:19)
>     at eval (webpack-internal:///./node_modules/epubjs/src/utils/queue.js:138:10)
> 
![error](https://github.com/user-attachments/assets/0e89f7c8-0469-449b-9b01-d9b28e9cff78)

以下是代码：
```vue
<template>
  <div>
    <div style="height: 100vh">
      <!-- 使用vue-reader -->
      <vue-reader :url="epub_url"> </vue-reader>

      <!-- 使用epubjs -->
      <!-- <div id="viewer" style="width: 600px; height: 800px"></div> -->
      <!-- <button @click="prevPage">上一页</button> -->
      <!-- <button @click="nextPage">下一页</button> -->
    </div>
  </div>
</template>

<script>
import { VueReader } from "vue-reader";
import ePub from "epubjs";
export default {
  components: { VueReader },
  data() {
    return {
      epub_url: "/viewer/file/1.epub",
      rendition: null,
    };
  },
  mounted() {
    // 使用epubjs
    const ebook = ePub(this.epub_url);
    this.rendition = ebook.renderTo("viewer", {
      width: "100%",
      height: "100%",
    });

    this.rendition.display();
  },

  methods: {
    // 下一页
    nextPage() {
      this.rendition.next();
    },
    // 上一页
    prevPage() {
      this.rendition.prev();
    },
  },
};
</script>

<style scoped>
</style>
```
vue-reader可以正常读取epub2.0，但试了几本epub3.0会报上面的错。
不过，直接使用epubjs是可以正常读取epub3.0的。

**Comment by jinhuan138** [comment]
> No Section Found

应该是epubjs的问题 
[seaction not found](https://github.com/futurepress/epub.js/issues/1214) 
[No Section Found](https://github.com/futurepress/epub.js/issues/1107)
